[build]
cmd = "cargo build && cp -r ./target/debug/idlefetch ./bin/idlefetch"

[[custom]]
name = "clean"
cmd = "cargo clean"
run = false

[[custom]]
name = "setup"
cmd = "mkdir -p bin && rustup install stable && rustup default stable"
run = false

[[custom]]
name = "release"
cmd = "cargo build --release && cp -r ./target/release/idlefetch ./bin/idlefetch"
run = false

[[pre]]
name = "fmt"
cmd = "cargo fmt"
